parameters:
    mopa_bootstrap.navbar.generic: Mopa\Bundle\BootstrapBundle\Navbar\GenericNavbar

services:
    mopa_bootstrap.navbar_renderer:
        class: Mopa\Bundle\BootstrapBundle\Navbar\Renderer\NavbarRenderer
        arguments: [ @service_container, [] ]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.renderer, alias: navbar }

    mopa_bootstrap.navbar.twig.extension:
        class: Mopa\Bundle\BootstrapBundle\Navbar\Twig\NavbarExtension
        arguments: [ @mopa_bootstrap.navbar_renderer ]
        tags:
            -  { name: twig.extension }
