language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
      - php: hhvm
      - env: SYMFONY_VERSION=dev-master
    exclude:
      - php: 5.3
        env: SYMFONY_VERSION=~2.7
      - php: 5.3
        env: SYMFONY_VERSION=dev-master
      - php: 5.4
        env: SYMFONY_VERSION=~2.7
      - php: 5.4
        env: SYMFONY_VERSION=dev-master

env:
  - SYMFONY_VERSION=~2.3.0
  - SYMFONY_VERSION=~2.7.0
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require --dev --no-interaction symfony/symfony:${SYMFONY_VERSION}
  - composer show -i

script:
  - phpunit

